services:
    rspace-chemistry:
        image: 'rspaceops/oss-chemistry:latest'
        restart: always
        volumes:
            - 'chemistry-files:/home/app'
        container_name: rspace-chemistry
volumes:
  chemistry-files:
