spring.application.name=chemistry
server.port=8090
search.file.dir=data
search.index.cron=0 0 00 * * *

scalar.enabled=true
scalar.path=/api-docs
scalar.url=v3/api-docs
springdoc.paths-to-exclude=${scalar.path},${scalar.path}/**
scalar.page-title=Chemistry API reference
scalar.favicon=favicon.png
scalar.telemetry=false
scalar.with-default-fonts=false
scalar.agent.disabled=true
scalar.mcp.disabled=true
scalar.hide-client-button=true
scalar.default-open-all-tags=true
scalar.show-developer-tools=never
scalar.custom-css=.darklight-reference a { display: none !important; }
