package com.researchspace.chemistry.image.generator;

import com.researchspace.chemistry.ChemistryException;
import com.researchspace.chemistry.image.ImageDTO;
import org.springframework.stereotype.Service;

/**
 * Image generator which uses Indigo to perform image generation from a chemical in its original format. Images
 * generated by this class will retain much of the information from the input, with the downside of lower success rate
 * (compared to other {@link ImageGenerator}s) of conversion from the original files.
 */
@Service
public class IndigoOriginalFormatImageGenerator extends BaseImageGenerator {
  private final IndigoImageUtils indigoImageUtils;

  public IndigoOriginalFormatImageGenerator(IndigoImageUtils indigoImageUtils) {
    this.indigoImageUtils = indigoImageUtils;
  }

  @Override
  public byte[] generateImage(ImageDTO imageDTO) {
    try {
      return indigoImageUtils.generateImage(imageDTO);
    } catch (ChemistryException e) {
      return handleError(IndigoOriginalFormatImageGenerator.class.getName(), e, imageDTO);
    }
  }
}
